baseURL: http://example.org/
languageCode: en-us
title: "Salayna's Blog"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 1

enableEmoji: true
params:
  background: images/site/mountain.jpg
  gitRepo: https://github.com/Salayna/Salayna.github.io
  enableBlogPost: true
