baseURL: https://salayna.github.io/
languageCode: fr-fr
title: "Salayna's Blog"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 1
googleAnalytics: G-KRWYM94MB3
disqusShortName: salayna
enableEmoji: true
params:
  background: images/site/Clay.png
  gitRepo: https://github.com/Salayna/Salayna.github.io
  enableBlogPost: true
