<<<<<<< HEAD
baseURL: https://salayna.github.io/
languageCode: fr-fr
=======
baseURL: http://example.org/
languageCode: en-us
>>>>>>> parent of ae7dca9... Publication
title: "Salayna's Blog"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 1

enableEmoji: true
params:
  background: images/site/clay.jpg
  gitRepo: https://github.com/Salayna/Salayna.github.io
  enableBlogPost: true
